### PR TITLE
Fix for cyberchef_url and addition of get_dict_values method

### PR DESCRIPTION
**Pull request by geekscrapy**

### CODE REVIEW

**Comment by geekscrapy** [comment]
Fixed, the issue was with urljoin - it needed the extra /

**Comment by geekscrapy** [comment]
It didn't in the original code...

**Comment by geekscrapy** [comment]
It actually returned `None` in the original code so left it as-is:
https://github.com/securisec/chepy/blob/8d4e8e68dd41e8ff1caabf6b20f7bbe3733c94f8/chepy/core.py#L640

I have since made it `return self`

**Comment by geekscrapy** [comment]
Can you provide some feedback why you closed this? Tests seem to pass and enables others to use custom locations of CyberChef?

**Comment by securisec** [comment]
@geekscrapy although the idea is good, and the implementation works, it was closed because the return type was not corrected. In the future, try to submit one pull request for each case instead of multiple changes in one pull request.

**Comment by geekscrapy** [comment]
It does contain the correct return result (self) unless I'm mistaken.... The changes tab shows this

**Pull request closed without merging**
